version: '3.8'

services:
  user_db:
    image: postgres:latest
    container_name: university-db
    ports:
      - "9002:5432"
    environment:
      POSTGRES_DB: university-ms
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: psw